ALTER TABLE leagues ADD COLUMN IF NOT EXISTS tournament_mode VARCHAR(20) NOT NULL DEFAULT 'combined';
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS season_type VARCHAR(20) DEFAULT 'year';
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS season_year VARCHAR(20);
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE leagues ADD COLUMN IF NOT EXISTS end_date DATE;
